[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/src/"
]

[profile.ci]
optimizer_runs = 1

[profile.production]
optimizer_runs = 10000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC}"
mainnet = "${MAINNET_RPC}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }